/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteProjectsRouteImport } from './routes/_site.projects'
import { Route as SiteJournalRouteImport } from './routes/_site.journal'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteApproachRouteImport } from './routes/_site.approach'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SiteJournalRoute = SiteJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteApproachRoute = SiteApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/approach': typeof SiteApproachRoute
  '/contact': typeof SiteContactRoute
  '/journal': typeof SiteJournalRoute
  '/projects': typeof SiteProjectsRoute
}
export interface FileRoutesByTo {
  '/approach': typeof SiteApproachRoute
  '/contact': typeof SiteContactRoute
  '/journal': typeof SiteJournalRoute
  '/projects': typeof SiteProjectsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/approach': typeof SiteApproachRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/journal': typeof SiteJournalRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/approach' | '/contact' | '/journal' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/approach' | '/contact' | '/journal' | '/projects' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/approach'
    | '/_site/contact'
    | '/_site/journal'
    | '/_site/projects'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/journal': {
      id: '/_site/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof SiteJournalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/approach': {
      id: '/_site/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof SiteApproachRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteApproachRoute: typeof SiteApproachRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteJournalRoute: typeof SiteJournalRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteApproachRoute: SiteApproachRoute,
  SiteContactRoute: SiteContactRoute,
  SiteJournalRoute: SiteJournalRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
